#!/usr/bin/env bash
#
# jumpstart.sh — build and run Podman Panel with one command.
#
# Auto-detects podman or docker, locates the engine socket, generates and
# persists strong secrets, builds the image if needed, and starts the container.
#
# Usage:
#   ./jumpstart.sh [--build]
#
# Overridable via environment:
#   ENGINE=podman|docker     force the container engine
#   PORT=3000                host port to publish
#   SOCKET=/path/to.sock     engine API socket (otherwise auto-detected)
#   COOKIE_SECURE=true       set when serving over HTTPS (behind a TLS proxy)
#
set -euo pipefail
cd "$(dirname "$0")"

IMAGE="podman-panel:latest"
CONTAINER="podman-panel"
ENV_FILE=".panel.env"
PORT="${PORT:-3000}"
COOKIE_SECURE="${COOKIE_SECURE:-false}"

FORCE_BUILD=0
[[ "${1:-}" == "--build" || "${1:-}" == "--rebuild" ]] && FORCE_BUILD=1

log() { printf '\033[36m▶ %s\033[0m\n' "$*"; }
die() { printf '\033[31m✗ %s\033[0m\n' "$*" >&2; exit 1; }

# Echoes the first existing podman socket path, if any.
podman_socket() {
  local s="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}/podman/podman.sock"
  if [[ -S "$s" ]]; then echo "$s"; elif [[ -S /run/podman/podman.sock ]]; then echo "/run/podman/podman.sock"; fi
}
has() { command -v "$1" >/dev/null 2>&1; }

# --- 1. pick an engine (prefer one with a live socket) ----------------------
ENGINE="${ENGINE:-}"
if [[ -z "$ENGINE" ]]; then
  if has podman && [[ -n "$(podman_socket)" ]]; then ENGINE="podman"
  elif has docker && [[ -S /var/run/docker.sock ]]; then ENGINE="docker"
  elif has podman; then ENGINE="podman"
  elif has docker; then ENGINE="docker"
  else die "Neither 'podman' nor 'docker' is installed."; fi
fi
has "$ENGINE" || die "Engine '$ENGINE' not found in PATH."
log "Engine: $ENGINE"

# --- 2. locate the API socket ----------------------------------------------
SOCKET="${SOCKET:-${PODMAN_SOCKET_PATH:-}}"
if [[ -z "$SOCKET" ]]; then
  if [[ "$ENGINE" == "podman" ]]; then
    SOCKET="$(podman_socket)"
    [[ -n "$SOCKET" ]] || die "Podman socket not found. Enable it with:
       systemctl --user enable --now podman.socket   (rootless)
       sudo systemctl enable --now podman.socket      (rootful)
   …or use Docker instead:  ENGINE=docker ./jumpstart.sh"
  else
    SOCKET="/var/run/docker.sock"
  fi
fi
[[ -S "$SOCKET" ]] || die "Engine socket '$SOCKET' does not exist or is not a socket."
log "Socket: $SOCKET"

# --- 3. secrets (generate once, then reuse) --------------------------------
gen() {
  if command -v openssl >/dev/null 2>&1; then openssl rand -hex "$1"
  else head -c "$1" /dev/urandom | od -An -tx1 | tr -d ' \n'; fi
}
if [[ -f "$ENV_FILE" ]]; then
  log "Reusing secrets from $ENV_FILE"
  # shellcheck disable=SC1090
  source "$ENV_FILE"
else
  log "Generating secrets → $ENV_FILE"
  SESSION_SECRET="$(gen 48)"
  SECRETS_KEY="$(gen 32)"
  ADMIN_USERNAME="${ADMIN_USERNAME:-admin}"
  ADMIN_PASSWORD="$(gen 12)"
  ( umask 077; cat > "$ENV_FILE" <<EOF
# Generated by jumpstart.sh — keep this file private. Delete it to rotate.
SESSION_SECRET=$SESSION_SECRET
SECRETS_KEY=$SECRETS_KEY
ADMIN_USERNAME=$ADMIN_USERNAME
ADMIN_PASSWORD=$ADMIN_PASSWORD
EOF
  )
fi

# --- 4. build the image if missing -----------------------------------------
if [[ "$FORCE_BUILD" == "1" ]] || ! "$ENGINE" image inspect "$IMAGE" >/dev/null 2>&1; then
  log "Building $IMAGE (this can take a few minutes the first time)…"
  "$ENGINE" build -t "$IMAGE" .
else
  log "Image $IMAGE already present (use --build to rebuild)."
fi

# --- 5. engine-specific socket access --------------------------------------
RUN_ARGS=()
if [[ "$ENGINE" == "docker" ]]; then
  gid="$(getent group docker 2>/dev/null | awk -F: '{print $3}')"
  [[ -n "$gid" ]] && RUN_ARGS+=(--group-add "$gid")
else
  # Rootless podman: map the host user into the container so it can read the socket.
  RUN_ARGS+=(--userns=keep-id)
fi

# --- 6. (re)create the container -------------------------------------------
if "$ENGINE" container inspect "$CONTAINER" >/dev/null 2>&1; then
  log "Replacing existing '$CONTAINER' container…"
  "$ENGINE" rm -f "$CONTAINER" >/dev/null
fi

log "Starting container…"
"$ENGINE" run -d --name "$CONTAINER" \
  --restart unless-stopped \
  -p "$PORT:3000" \
  "${RUN_ARGS[@]}" \
  -e SESSION_SECRET="$SESSION_SECRET" \
  -e SECRETS_KEY="$SECRETS_KEY" \
  -e ADMIN_USERNAME="$ADMIN_USERNAME" \
  -e ADMIN_PASSWORD="$ADMIN_PASSWORD" \
  -e COOKIE_SECURE="$COOKIE_SECURE" \
  -e PODMAN_SOCKET_PATH=/var/run/docker.sock \
  -v "$SOCKET:/var/run/docker.sock" \
  -v panel-data:/app/data \
  "$IMAGE" >/dev/null

# --- 7. wait until it serves -----------------------------------------------
if command -v curl >/dev/null 2>&1; then
  printf '▶ Waiting for the panel'
  ready=0
  for _ in $(seq 1 60); do
    if curl -fsS -o /dev/null "http://127.0.0.1:$PORT/login" 2>/dev/null; then ready=1; break; fi
    if ! "$ENGINE" ps --filter "name=$CONTAINER" --filter status=running -q | grep -q .; then
      printf '\n'; "$ENGINE" logs "$CONTAINER" 2>&1 | tail -n 20; die "Container exited unexpectedly."
    fi
    printf '.'; sleep 1
  done
  printf '\n'
  [[ "$ready" == "1" ]] || { "$ENGINE" logs "$CONTAINER" 2>&1 | tail -n 20; die "Timed out waiting for the panel."; }
fi

# --- 8. summary -------------------------------------------------------------
cat <<EOF

✅ Podman Panel is running.

   URL       http://localhost:$PORT
   Username  $ADMIN_USERNAME
   Password  $ADMIN_PASSWORD
             (initial bootstrap password — you must change it on first login;
              ignore if you have already set your own)

   Engine    $ENGINE   ·   socket $SOCKET
   Secrets   $ENV_FILE (reused on the next run; delete to rotate)

   Logs      $ENGINE logs -f $CONTAINER
   Stop      $ENGINE stop $CONTAINER
   Rebuild   ./jumpstart.sh --build
EOF
